project:
  type: website
  output-dir: docs   # ensures GitHub Pages will work

website:
  title: "babyPHONO"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

