project:
  type: website
  output-dir: docs   # ensures GitHub Pages will work

website:
  title: "babyPHONO"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

    background: purple
  
    foreground: white
    
    logo: images/babyphono_logo_purple.png
    
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

